'use client';

import { useEffect, useRef, useState } from 'react';
import {
  Boxes,
  Package,
  IndianRupee,
  AlertTriangle,
} from 'lucide-react';

import BaseModal from '../ui/BaseModal';
import InventoryFormField from '../ui/InventoryFormField';

import type {
  InventoryItem,
  EditInventoryPayload,
} from '../../types/inventory';

interface Props {
  item: InventoryItem | null;
  onClose: () => void;
  onSubmit: (
    id: number,
    payload: EditInventoryPayload
  ) => Promise<void>;
}

const EMPTY: EditInventoryPayload = {
  partName: '',
  category: '',
  retailPrice: 0,
  lowStockAlert: 5,
};

export default function EditInventoryForm({
  item,
  onClose,
  onSubmit,
}: Props) {
  const [form, setForm] =
    useState<EditInventoryPayload>(EMPTY);

  const [saving, setSaving] = useState(false);

  const [error, setError] =
    useState<string | null>(null);

  const syncedId = useRef<number | null>(null);

  useEffect(() => {
    if (!item) return;

    if (syncedId.current === item.id) return;

syncedId.current = item.id;

    setForm({
      partName: item.partName,
      category: item.category,
      retailPrice: item.retailPrice,
      lowStockAlert: item.lowStockAlert,
    });

    setError(null);
  }, [item]);

  if (!item) return null;

const inventoryItem = item;

  function patch<K extends keyof EditInventoryPayload>(
    key: K,
    value: EditInventoryPayload[K]
  ) {
    setForm((prev) => ({
      ...prev,
      [key]: value,
    }));
  }

  async function handleSubmit(
    e: React.FormEvent
  ) {
    e.preventDefault();

    setSaving(true);
    setError(null);

    try {
      await onSubmit(inventoryItem.id , form);

      onClose();
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : 'Unable to update inventory item.'
      );
    } finally {
      setSaving(false);
    }
  }

  return (
    <BaseModal
      open={!!inventoryItem}
      onClose={onClose}
      loading={saving}
      size="lg"
      title="Edit Inventory Item"
      description="Update inventory information."
      icon={<Boxes size={20} />}
      footer={
        <div className="flex gap-3">
          <button
            type="button"
            onClick={onClose}
            disabled={saving}
            className="
flex-1
rounded-xl
border
border-gray-200
py-3
font-medium
text-gray-700
transition
hover:bg-gray-100
disabled:opacity-50
"
          >
            Cancel
          </button>

          <button
            type="submit"
            form="edit-inventory-form"
            disabled={saving}
            className="
flex-1
rounded-xl
bg-blue-600
py-3
font-semibold
text-white
transition
hover:bg-blue-700
disabled:opacity-60
"
          >
            {saving
              ? 'Saving...'
              : 'Save Changes'}
          </button>
        </div>
      }
    >
      <form
        id="edit-inventory-form"
        onSubmit={handleSubmit}
        className="space-y-5"
      >
        {error && (
          <div
            className="
rounded-xl
border
border-red-200
bg-red-50
px-4
py-3
text-sm
font-medium
text-red-600
"
          >
            {error}
          </div>
        )}

        <div
          className="
rounded-xl
border
border-gray-200
bg-gray-50
p-4
"
        >
          <p className="text-xs text-gray-500">
            SKU
          </p>

          <p
            className="
mt-1
font-mono
font-semibold
text-gray-800
"
          >
            {item.sku}
          </p>

          <p className="mt-2 text-xs text-gray-400">
            SKU is generated by the server and
            cannot be changed.
          </p>
        </div>

        <InventoryFormField
          required
          label="Part Name"
          value={form.partName}
          icon={<Package size={18} />}
          onChange={(e) =>
            patch(
              'partName',
              e.target.value
            )
          }
        />

        <InventoryFormField
          required
          label="Category"
          value={form.category}
          onChange={(e) =>
            patch(
              'category',
              e.target.value
            )
          }
        />

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <InventoryFormField
            required
            label="Retail Price"
            type="number"
            min={0}
            step="0.01"
            icon={<IndianRupee size={18} />}
            value={form.retailPrice}
            onChange={(e) =>
              patch(
                'retailPrice',
                Number(e.target.value)
              )
            }
          />

          <InventoryFormField
            required
            label="Low Stock Alert"
            type="number"
            min={0}
            icon={<AlertTriangle size={18} />}
            value={form.lowStockAlert}
            onChange={(e) =>
              patch(
                'lowStockAlert',
                Number(e.target.value)
              )
            }
          />
        </div>
      </form>
    </BaseModal>
  );
}