'use client';

import React, { useState } from 'react';
import { X } from 'lucide-react';
import type { AddInventoryPayload } from '../../types/inventory';

interface Props {
  open: boolean;
  onClose: () => void;
  onSubmit: (payload: AddInventoryPayload) => Promise<string>;
}

const EMPTY: AddInventoryPayload = {
  partName: '',
  category: '',
  stockLevel: 0,
  retailPrice: 0,
  lowStockAlert: 5,
};

export default function AddInventoryModal({ open, onClose, onSubmit }: Props) {
  const [form, setForm] = useState<AddInventoryPayload>(EMPTY);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!open) return null;

  function patch<K extends keyof AddInventoryPayload>(key: K, value: AddInventoryPayload[K]) {
    setForm((f) => ({ ...f, [key]: value }));
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setSaving(true);
    setError(null);
    try {
      const sku = await onSubmit(form);
      alert(`Part added! Auto-generated SKU: ${sku}`);
      setForm(EMPTY);
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add item.');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100">
          <h2 className="text-base font-semibold text-gray-900">Add New Part</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          {error && (
            <div className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
              {error}
            </div>
          )}

          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="block text-xs font-semibold text-gray-600 mb-1">Part Name</label>
              <input
                required
                value={form.partName}
                onChange={(e) => patch('partName', e.target.value)}
                placeholder="e.g. Ather Brake Pads"
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div className="col-span-2">
              <label className="block text-xs font-semibold text-gray-600 mb-1">Category</label>
              <input
                required
                value={form.category}
                onChange={(e) => patch('category', e.target.value)}
                placeholder="e.g. Consumables, Electrical"
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1">Initial Stock</label>
              <input
                required
                type="number"
                min={0}
                value={form.stockLevel}
                onChange={(e) => patch('stockLevel', Number(e.target.value))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-gray-600 mb-1">Retail Price (₹)</label>
              <input
                required
                type="number"
                step="0.01"
                min={0}
                value={form.retailPrice}
                onChange={(e) => patch('retailPrice', Number(e.target.value))}
                placeholder="0.00"
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div className="col-span-2">
              <label className="block text-xs font-semibold text-gray-600 mb-1">Low Stock Threshold</label>
              <input
                required
                type="number"
                min={0}
                value={form.lowStockAlert}
                onChange={(e) => patch('lowStockAlert', Number(e.target.value))}
                className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>

          <p className="text-xs text-gray-400">
            SKU will be auto-generated by the server based on category.
          </p>

          {/* Footer */}
          <div className="flex justify-end gap-3 pt-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-sm text-gray-600 rounded-lg border border-gray-200 hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 text-sm font-semibold text-white bg-blue-600 rounded-lg hover:bg-blue-700 disabled:opacity-60 transition-colors"
            >
              {saving ? 'Saving…' : 'Add Part'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
