'use client';
import { ChevronLeft, ChevronRight, Eye, MoreHorizontal, Printer, Search, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { InvoiceRecord } from '../types/billing';
import { formatCurrency } from '../utils/calculateInvoice';

const PAGE_SIZE = 6;
export default function InvoiceHistory({ invoices, onView, onPrint, onMarkPaid, onDelete }: { invoices: InvoiceRecord[]; onView: (invoice: InvoiceRecord) => void; onPrint: (invoice: InvoiceRecord) => void; onMarkPaid: (invoice: InvoiceRecord) => void; onDelete: (invoice: InvoiceRecord) => void }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('ALL'); const [date, setDate] = useState(''); const [page, setPage] = useState(1); const [menu, setMenu] = useState<number | null>(null);
  const filtered = useMemo(() => invoices.filter((invoice) => {
    const needle = query.toLowerCase(); const matchesSearch = [invoice.invoiceNo, invoice.customerName, invoice.ticket?.vehicle?.vehicleModel].some((value) => value?.toLowerCase().includes(needle));
    return matchesSearch && (status === 'ALL' || invoice.paymentStatus === status) && (!date || invoice.createdAt.slice(0, 10) === date);
  }), [invoices, query, status, date]);
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const rows = filtered.slice((Math.min(page, pages) - 1) * PAGE_SIZE, Math.min(page, pages) * PAGE_SIZE);
  return <section className="rounded-2xl border border-[#dedbd8] bg-white" aria-labelledby="history-heading"><div className="border-b border-[#e7e3df] p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#006a63]">Ledger</p><h2 id="history-heading" className="mt-1 text-xl font-bold text-[#091426]">Invoice history</h2></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search className="absolute left-3 top-2.5 text-[#8a8b90]" size={17}/><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} className="w-full rounded-xl border border-[#d9d6d2] py-2 pl-9 pr-3 text-sm outline-none focus:border-[#006a63] sm:w-56" placeholder="Search invoices"/></label><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="rounded-xl border border-[#d9d6d2] px-3 py-2 text-sm"><option value="ALL">All statuses</option><option value="PAID">Paid</option><option value="UNPAID">Unpaid</option></select><input type="date" value={date} onChange={(e) => { setDate(e.target.value); setPage(1); }} className="rounded-xl border border-[#d9d6d2] px-3 py-2 text-sm"/></div></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#f7f5f3] text-[10px] uppercase tracking-wider text-[#75777d]"><tr>{['Invoice no.', 'Customer', 'Vehicle', 'Date', 'Total', 'Status', 'Method', 'Actions'].map((h) => <th key={h} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{rows.map((invoice) => <tr key={invoice.id} className="border-t border-[#eeeae7] text-[#45474c] hover:bg-[#fcfbfa]"><td className="px-5 py-4 font-mono text-xs font-bold text-[#006a63]">{invoice.invoiceNo}</td><td className="px-5 py-4"><b className="text-[#091426]">{invoice.customerName}</b><small className="block text-[#8a8b90]">{invoice.customerPhone}</small></td><td className="px-5 py-4">{invoice.ticket?.vehicle?.vehicleModel || (invoice.saleType === 'COUNTER' ? 'Counter sale' : '—')}</td><td className="px-5 py-4">{new Date(invoice.createdAt).toLocaleDateString('en-IN')}</td><td className="px-5 py-4 font-bold text-[#091426]">{formatCurrency(invoice.grandTotal)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${invoice.paymentStatus === 'PAID' ? 'bg-[#d7f4ef] text-[#006a63]' : 'bg-[#fff0d9] text-[#7a4f00]'}`}>{invoice.paymentStatus}</span></td><td className="px-5 py-4 text-xs font-semibold">{invoice.paymentMethod.replace('_', ' ')}</td><td className="relative px-5 py-4"><button onClick={() => setMenu(menu === invoice.id ? null : invoice.id)} className="rounded-lg border p-2 hover:bg-[#f2f0ef]"><MoreHorizontal size={16}/></button>{menu === invoice.id && <div className="absolute right-5 top-12 z-20 w-40 rounded-xl border bg-white p-1.5 shadow-xl"><button onClick={() => { onView(invoice); setMenu(null); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold hover:bg-[#f4f2f0]"><Eye size={14}/>View details</button><button onClick={() => { onPrint(invoice); setMenu(null); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold hover:bg-[#f4f2f0]"><Printer size={14}/>Print again</button>{invoice.paymentStatus !== 'PAID' && <button onClick={() => { onMarkPaid(invoice); setMenu(null); }} className="flex w-full rounded-lg px-3 py-2 text-xs font-semibold text-[#006a63] hover:bg-[#e8f7f4]">Mark paid</button>}<button onClick={() => { onDelete(invoice); setMenu(null); }} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold text-[#ba1a1a] hover:bg-[#fff1ef]"><Trash2 size={14}/>Delete</button></div>}</td></tr>)}{!rows.length && <tr><td colSpan={8} className="p-10 text-center text-sm text-[#75777d]">No invoices match these filters.</td></tr>}</tbody></table></div>
    <div className="flex items-center justify-between border-t px-5 py-4 text-xs text-[#75777d]"><span>Showing {rows.length} of {filtered.length}</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage((p) => p - 1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronLeft size={15}/></button><span className="font-semibold text-[#45474c]">Page {Math.min(page, pages)} of {pages}</span><button disabled={page >= pages} onClick={() => setPage((p) => p + 1)} className="rounded-lg border p-2 disabled:opacity-30"><ChevronRight size={15}/></button></div></div>
  </section>;
}
