import type { InvoiceDraft, InvoiceRecord } from '../types/billing';
import { calculateInvoice, discountFromItems, formatCurrency, normalizeItems, visibleItems } from '../utils/calculateInvoice';

export default function InvoicePreview({ draft, invoice }: { draft?: InvoiceDraft; invoice?: InvoiceRecord }) {
  const items = draft?.items || normalizeItems(invoice?.items);
  const savedDiscount = discountFromItems(items);
  const totals = draft ? calculateInvoice(draft) : { subtotal: visibleItems(items).reduce((s, i) => s + i.qty * i.price, 0), labor: invoice?.laborCharge || 0, discount: savedDiscount, grandTotal: invoice?.grandTotal || 0 };
  return <div id="invoice-print-area" className="rounded-2xl border border-[#dedbd8] bg-white p-6 text-[#091426] shadow-xl print:border-0 print:shadow-none">
    <div className="flex justify-between gap-4 border-b border-[#e7e3df] pb-5"><div><div className="text-2xl font-black">VoltOps</div><p className="mt-1 text-xs text-[#75777d]">EV Repair Systems · Tax Invoice</p></div><div className="text-right"><p className="font-mono text-sm font-bold">{invoice?.invoiceNo || 'DRAFT INVOICE'}</p><p className="mt-1 text-xs text-[#75777d]">{invoice?.createdAt ? new Date(invoice.createdAt).toLocaleDateString('en-IN') : 'Preview'}</p></div></div>
    <div className="grid gap-4 border-b border-[#e7e3df] py-5 text-sm sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-widest text-[#75777d]">Bill to</p><p className="mt-1 font-bold">{draft?.customerName || invoice?.customerName}</p><p className="text-[#61636a]">{draft?.customerPhone || invoice?.customerPhone}</p></div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-widest text-[#75777d]">Vehicle / Ticket</p><p className="mt-1 font-bold">{draft?.vehicle || invoice?.ticket?.vehicle?.vehicleModel || (invoice?.saleType === 'COUNTER' ? 'Counter sale' : '—')}</p><p className="text-[#61636a]">{draft?.ticketId ? `EV-${String(draft.ticketId).padStart(4, '0')}` : invoice?.ticketId ? `EV-${String(invoice.ticketId).padStart(4, '0')}` : 'Walk-in purchase'}</p></div></div>
    <div className="py-5"><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b pb-2 text-[10px] font-bold uppercase tracking-wider text-[#75777d]"><span>Description</span><span>Qty</span><span className="w-24 text-right">Amount</span></div>{visibleItems(items).map((item, index) => <div key={`${item.sku}-${index}`} className="grid grid-cols-[1fr_auto_auto] gap-3 border-b border-[#f0eeec] py-3 text-sm"><span><b>{item.name}</b><small className="block font-mono text-[10px] text-[#8a8b90]">{item.sku}</small></span><span>{item.qty}</span><span className="w-24 text-right font-semibold">{formatCurrency(item.qty * item.price)}</span></div>)}</div>
    <div className="ml-auto w-full max-w-xs space-y-2 text-sm"><div className="flex justify-between"><span className="text-[#61636a]">Parts subtotal</span><span>{formatCurrency(totals.subtotal)}</span></div><div className="flex justify-between"><span className="text-[#61636a]">Labor</span><span>{formatCurrency(totals.labor)}</span></div>{totals.discount > 0 && <div className="flex justify-between text-[#ba1a1a]"><span>Discount</span><span>− {formatCurrency(totals.discount)}</span></div>}<div className="flex justify-between border-t pt-3 text-lg font-black"><span>Grand total</span><span>{formatCurrency(totals.grandTotal)}</span></div></div>
    {(draft?.notes || draft?.repairSummary) && <div className="mt-6 rounded-xl bg-[#f5f3f1] p-4 text-xs text-[#61636a]"><b className="text-[#091426]">Service notes</b><p className="mt-1">{draft.repairSummary}</p>{draft.notes && <p className="mt-1">{draft.notes}</p>}</div>}
  </div>;
}
